Repository Servatom/notefy, pull requests merged in 2021-10, with the labels that each got.

#63 Responsive dashboard
  frontend/src/assets/css/Dashboard.css
  frontend/src/assets/css/Notes.css
  frontend/src/assets/css/Searchbar.css
  frontend/src/assets/css/Sidenav.css
  frontend/src/components/SideNav.js
  frontend/src/pages/Dashboard.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#85 fix: word-count-add-note
  frontend/src/components/AddNote.js
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#93 Added subtle hover effects to the notes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/assets/css/Notes.css
  frontend/src/components/Note.js
Labels: enhancement, hacktoberfest-accepted

#120 Add alert for server error
  frontend/src/App.js
  frontend/src/pages/Dashboard.js
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
